### ISSUE TITLE
try~catchの使い方

### ISSUE THREAD

**Issue by owl9218** [tsu-nera/ask-me-anything#2]
javaにてtry~catchの正しい記述法を教えていただけますか？
また、何度か接続する際に毎回記述しなければいけないのでしょうか？
まとめられたりしますか？

**Comment by tsu-nera** [comment]
> javaにてtry~catchの正しい記述法を教えていただけますか？

すみません、わたしも専門でやっていたわけではないので、ネットで調べました。
以下を参照してください。

* [リソースは finally ブロックで閉じる \| まくまくいろいろノート](https://maku77.github.io/memo/finally-close.html)
* [JDBC \(2\)](http://www.rsch.tuis.ac.jp/~nagai/SYS/SYS18_new1.html)

どちらも、短くまとまっていると思います。

基本的に、入れ子は2重までで、3重になったらなにか回避方法がないか考えたほうがいいです。

**Comment by tsu-nera** [comment]
> また、何度か接続する際に毎回記述しなければいけないのでしょうか？
> まとめられたりしますか？

シングルプロセスならばいいのですが、マルチプロセス、マルチスレッドの場合（つまり複数の箇所から接続する場合 )、接続は使うたびに毎回書きます。WEBサービスなので、当然同時アクセスがあると思います（ちょっとJavaのwebサーバの仕組みは把握していなくて間違っているかもしれませんが、複数前提でかんがえたほうがいい）

接続を使いまわすほうほうとして、コネクションプールという手法があります。
* [いまふたたびのJDBC \- Qiita](https://qiita.com/kimullaa/items/bb3af4f6557e77d6acc1#jdbc%E3%82%B3%E3%83%8D%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%83%97%E3%83%BC%E3%83%AB)

**Comment by tsu-nera** [comment]
転載

> 後は何とかやってみます。この度はお手数おかけしました。ありがとうございます！
